### ISSUE TITLE
Create Metalsmith Example

### ISSUE THREAD

**Issue by EvanLovely** [remotesynth/Static-Site-Samples#1]
It'd be great to see [Metalsmith](https://www.metalsmith.io) implemented!

**Comment by iabw** [comment]
I thought the same thing, saw your issue, and decided to sit down and do it. It's about 75% done. Should file a pull request tomorrow evening.

**Comment by EvanLovely** [comment]
Nice! Looking forward to it!

**Comment by remotesynth** [comment]
I am working on one actually. Hope to have it in time for Fluent next week.

**Comment by remotesynth** [comment]
Ok. I have committed an initial Metalsmith example site. Please note that while the project is complete, there are some known issues listed in the project readme. https://github.com/remotesynth/Static-Site-Samples/commit/80bfef6f7d1a45aa23e2a1e600ce5d1b13cef79d
