### ISSUE TITLE
Hugo fails to render links with parenthesis as last character correctly

### ISSUE THREAD

**Issue by riyad** [remotesynth/Static-Site-Samples#5]
The Food Chain episode page contains a link with nested parentheses:

``` markdown
Back into the reality, Finn realizes the lesson of the Food Chain and sings "[Food Chain](http://adventuretime.wikia.com/wiki/Food_Chain_(song))", which PB soon joins singing with him.
```

Hugo will misinterpret the first closing parenthesis as "end of link" and produce a link to `http://adventuretime.wikia.com/wiki/Food_Chain_(song` adding the remaining `)` as extra text after the link. Effectively rendering it as
`<a href="http://adventuretime.wikia.com/wiki/Food_Chain_(song">Food Chain</a>)`.

I don't know if this should
- be fixed by escaping the parentheses
- by reporting it upstream
- by leaving it as an example of things that fail in unexpected ways

😐

**Comment by remotesynth** [comment]
Thanks. Escaping the URL fixed the issue. https://github.com/remotesynth/Static-Site-Samples/commit/89dd6cc8d3957f9f6b6c5e371cd20cc6c634b0c5
